server:
  port: 8082

spring:
  application:
    name: atm-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能
          lower-case-service-id: true  # 使用小写服务名，默认是大写
      routes:
        - id: auth-service
          uri: lb://atm-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://atm-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: check-service
          uri: lb://atm-check
          predicates:
            - Path=/check/**
          filters:
            - StripPrefix=1
        - id: report-service
          uri: lb://atm-report
          predicates:
            - Path=/report/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka/}
  instance:
    prefer-ip-address: true 