server:
  port: 8889  # 网关服务端口

spring:
  application:
    name: atm-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启服务注册发现，自动路由
          lower-case-service-id: true  # 小写 serviceId 适配前端路径
      routes:
        - id: auth-service
          uri: lb://atm-auth  # 修改为使用服务名称
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://atm-user  # 修改为使用服务名称
          predicates:
            - Path=/users/**
        - id: check-service
          uri: lb://atm-check  # 修改为使用服务名称
          predicates:
            - Path=/attendance/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}