server:
  port: 8080

  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

logging:
  level:
    com.tss.atm: DEBUG
    org.springframework.web: INFO
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atm_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: rw123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.tss.atm.user.entity
  # ⚠️ 这个应该是实体类的包，不是 Mapper 的包
