spring:
  application:
    name: atm-config
  profiles:
    active: dev
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/{application}
          fail-fast: true

server:
  port: ${CONFIG_SERVER_PORT:8888}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always 