spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atm_db?useSSL=false&serverTimezone=UTC
    username: root
    password: rw123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000