spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userDemo?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Renwei123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: your-app-name  # 配置文件将根据该名称从 config server 中获取

    cloud:
      config:
        uri: http://localhost:8888  # Config Server 地址

  spring:
    application:
      name: your-service-name  # 客户端的服务名称

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/  # Eureka Server 的地址
      fetchRegistry: true  # 是否从 Eureka Server 拉取服务信息
      registerWithEureka: true  # 向 Eureka 注册

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



