server:
  port: 8761

spring:
  application:
<<<<<<< HEAD
    name: atm-eureka-server
  security:
    user:
      name: eureka
      password: password
  security:
    user:
      name: eureka
      password: password
    basic:
      enabled: false
=======
    name: atm-eureka
>>>>>>> a766473db144e890be6e5d824383fa312bdbeca1

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
<<<<<<< HEAD
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
=======
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://${eureka.instance.hostname}:${server.port}/eureka/} 
>>>>>>> a766473db144e890be6e5d824383fa312bdbeca1
