server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userDemo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Renwei123
    driver-class-name: com.mysql.cj.jdbc.Driver

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.tss.atm.user.entity  # ⚠️ 这个应该是实体类的包，不是 Mapper 的包
